[package]
name = "deno-libhydrogen"
version = "0.0.0"
authors = ["@chiefbiiko <noah.anabiik.schwarz@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.35.0"
libhydrogen = "0.2.1"
lazy_static = "1.4.0"