name: ci

on: push

jobs:
  test:
    name: test deno-libhydrogen on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: clone repo
        uses: actions/checkout@v2.0.0
      - name: install rust n co
        uses: hecrj/setup-rust-action@v1.3.2
        with:
          rust-version: stable
      - name: install deno
        uses: denolib/setup-deno@v1.2.0
        with:
          deno-version: 0.36.0
      - name: build plugin
        run: cargo build
      - name: run tests
        run: deno test --allow-plugin
