name: ci-windows

on: push

jobs:
  test:
    name: test deno-libhydrogen on windows-latest
    runs-on: windows-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2.0.0
      - name: install deno
        uses: denolib/setup-deno@v1.2.0
        with:
          deno-version: 0.36.0
      - name: install llvm
        run: choco install llvm -y
      - name: set up python 2.7.17
        uses: actions/setup-python@v1.2.0
        with:
          python-version: 2.7.17
      - name: build plugin
        run: cargo build
      - name: run tests
        run: deno test --allow-plugin